language: node_js
node_js:
 - "node"

notifications:
  email:
    recipients:
      - risause4@gmail.com
      #- annaji33@gmail.com
    #if: branch = master
    on_success: always
    on_failure: always # default: always