language: node_js
node_js:
 - "node"
dist: trusty
addons:
  chrome: stable
before_install:
  - npm build; npm start; 
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
notifications:
  email:
    recipients:
      - risause4@gmail.com
      - annaji33@gmail.com
    if: branch = master
    on_success: always # default: change
    on_failure: always # default: always
    if: branch = dev 
    on_failure: always